return PlaceObj('ModDef', {
	'title', "Rato's Gameplay Balance and Overhaul 3",
	'description', "[h1]Rato's Balance and Overhaul:[/h1]\n\nBig thanks to playtesters for giving valuable feedback:\n[list]\n[*][b]mousetrapreplica[TSC][/b] - who has been playtesting this mod since almost the beginning\n[*][b]Starbuck[/b]\n[*][b]Caladan[/b]\n[*][b]Player One[/b]\n[*][b]infiniteMotion[/b]\n[*][b]redparadize[/b]\n[*][b]KreNich[/b]\n[*]and many others\n[/list]\n\nAlso [b]Toni[/b] and [b]MantisClaw[/b], gun experts from Discord\n\nIf you want to buy me a coffee you can do so here: https://www.buymeacoffee.com/rato_modder\n\n\n\nThis mod aims to provide a balanced but very challenging experience, improving depth of gameplay, [b]increasing lethality[/b] and incorporating some realistic mechanics. [b]Auto fire modes have full bullet damage, and single shots have more chance of critical hit[/b]. Guns are balanced by their score and are unique; explosives are not perfectly accurate; and fights realistically lead to incapacitation prior to death by new wounding and bleeding mechanics.\n\n\n[b]Please use a fresh savegame with this mod, so that the components will have their proper effects and to avoid bugs.\n\nIt is also recommended to not use an Ironman mode save[/b]\n\n\n[b]Compatibility patches[/b]:\nwith mariOlof's Tactical Enemy. Use this to have the components and new weapons/calibers drop by enemies.\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3028233953\n\nWith ToG. Add Tons of Guns\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3101203757\n\nIf you have ToG and ToC loaded, this mod will use some custom visuals for the added scopes. Recommended\n\nCompatible with Smart Overwatch - really recommended  \nCompatible with Descriptive CTH\n\n\n\n[hr][/hr]\n\n[b]Penalties can be customized in mod options[/b]\n\n\n[h1]Gun overhaul overview:[/h1]\n\n[list]\n\n[*][b]Aiming Rework[/b]: Mercs with low [b]Hand-Eye Coordination[/b] (Dex + Marks) will get less benefits from aim bonus.\n\n[*][b]Shooting Stance[/b]: you need to spend AP to shoulder your weapon to aim. This will create an angle where you can shoot more accurately. If you aim outsde the angle, you must spend AP to rotate. Unaimed shots now have Hipfire penalty. 1 aim level shots have Snapshot penalty. OW action can be used to prepare weapon when you dont have enough AP to shoot. Component weight or barrel length can reduce shooting angle. Inspired by [b]Wax's[/b] mod.\n\n[*]Weapons have rotation angles based on real life weight and barrel length.\n\n[*]New mechanics and components permit you to make your weapon into a [b]hybrid[/b]: rip the stock off your rifle to make it deadly and fast at close range - like a SMG -, or mount a sniper scope and heavy barrel to have precise single headshots at a distance.\n\n[*]New calibers introduced: [b]5.45x39mm, 7.92x57mm and the 7.62x54Rmm[/b]\n\n[*]Correct magazine and expanded magazine sizes.\n\n[*]Weapon calibers are realistic, so two weapons with the same caliber will have very similar damage. There is room for variations depending on the class of the weapon or other aspects.\n\n[*]Penetration depends on the caliber.\n\n[*]There have been changes to make each weapon unique. Even direct upgrades have differences that can make them worse for specific builds.\n\n[*]Weapons classes were changed to dominate a specific range and have a specific function.\n\n\n[/list]\n\n[h1]Ammo Overhaul:[/h1]\n[list]\n[*]5.45 rounds now have [b]tumbling[/b] effect, which increase critical chance \n[*]5.56 rounds have [b]fragmentation[/b] effect, which increase critical damage \n[*]AP rounds now have decreased critical damage and increased recoil\n[*]Match rounds have increased aim, range, and Critical Scaling\n[*]Tracer rounds apply Marked, Revealed and are easier to compensate recoil\n[*]HP rounds now have increased critical damage (instead of chance)\n\n[/list]\n[b]Check the discussion posts for details of gameplay changes like[/b]:\n\n[h1]New systems based on attributes[/h1]\n\n[B]New multishot systems[/b]\n\nFull damage in all forms of Automatic Fire\n\n[*][b]New recoil system [/b]: \n\nCTH is decreased shot by shot.\n\nScales with [b]Strength[/b] and [b]Marksmanship[/b], diferent scaling for calibers. All calibers have a [b]Recoil Breakpoint[/b] in Str: if you are below this str level the penalties will be even higher per point. It also represents a flat component of the recoil, so the higher the breakpoint, the higher will be the overral penalty to hit\n\n[*][b]Autofire[/b]: shoots 10 bullets, has fixed AP cost, can be aimed once.\n\n[*][b]MG burst rework [/b]: Shoots 6 bullets. [b]Strength[/b] has more impact on determining accuracy of the MG.\n\n[*][b]Run and Gun reworked[/b]: lethal at close range, has big recoil accuracy penalty at distance. The move range depends on agility and bulk of the weapon\n\nOther changes:\n\n[*][b]Dual Fire rework[/b]: Max aim = 1, AP cost reduced. Dexterity reduces penalty. Higher penalty at distance.\n\n[*][b]Low Cover effect is increased[/b].\n\n[*][b]Sight Radius is increased[/b].\n\n[*][b]Shot Crit bonus[/b]: firearms have critical bonus chance that scales with [b]Dexterity+Marksmanship[/b]. The effect is based on aim level. Single shot have significant more scaling.\n\n[*][b]Targeted shot bonus reworked[/b]: Applies when fully aimed. Scales with [i][b]Composure[/b][/i] (compost of Marksmanship and Wisdom). Snipers have better scaling. Single shot has better scaling.\n\n[*][b]Melee range shooting penalty[/b]: long barrels make it harder to hit at melee range, while short ones make it easier.\n\n[b]Weapon class:[/b]\n\n[list]\n[*][b]9mm pistols[/b]:  Low range, low damage, good aiming. [b]Recover half free move AP after firing[/b]\n[*] [b]Snipers[/b]: have very high critical damage scaling. High aim and range, medium damage. Good at targeting body parts. Bolt action snipers are exceptional at targeting body parts.\n[*] [b]SMGs[/b]: have extra 10% damage against flanked targets. Medium-low range, medium aim, medium damage [b]Recover half free move AP after firing[/b]\n[*][b]ARs[/b]: have good damage with new burst fire changes. Bullpup rifles have less recoil.\n[*][b]MGs[/b]: have been rebalanced, have good damage and overwatch, low aim and medium range. \n[*][b]Shotguns[/b]: have extreme damage, low range, medium aim. The cone is less wide and the range has been improved. Flechette and saltshot ammo reworked.\n[*][b]Revolvers[/b]: have medium range, medium damage, good critical scaling and good aim. \n[/list]\n\n[h1] Scope and component overhaul [/h1]\nWhat really makes a sniper weapon? [b]A precision scope[/b].\n\nScopes now give a high range bonus. They come in 5 magnification scales, check the [b]discussion posts[/b] for information about scopes and components.\n\nThe higher magnification scopes now give a penalty when shooting at close range. The penalty is proportional to the bonus range, and get progressively higher the closer you are to the target. \n\nBeware, choosing a scope now [b]is making a commitment[/b], and the penalties can be very severe at close range with the higher magnification ones.\n\nWant to make a semi auto for close range? Or an assault rifle to one tap at distance? Now you can. \n\n[h1]Stealth overhaul:[/h1]\n\n        Suppressors no longer completely silence your gun, they cut the noise radius by half. To effectively sneak, you need to use Subsonic ammo now, a type of bullet designed to travel slowly and be less loud.\n\n        [b]It's harder to do a stealth kill on aware opponents.[/b]\n\n		 [b]Enemy detection range is increased.[/b]\n		\n\n\n[h1]Optional Addons (Recommended):[/h1]\n\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3028029624 Wounding Overhaul\n\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3253652174 [b]NEW[/b] Explosives Overhaul 2.0\n\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3087514348 Cash economy customizer\n\n[h1]Collection of recommended mods by other creators:[/h1]\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3024439779",
	'image', "Mod/cfahRED/Images/rat mod315.png",
	'external_links', {
		"https://www.buymeacoffee.com/rato_modder",
	},
	'last_changes', "3.49a -  not released\n\nfixed steyr scout suppresor having no sound",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "Tc3ajdY",
			'title', "Zulib Weapons Core",
		}),
	},
	'id', "cfahRED",
	'author', "rato",
	'version_major', 3,
	'version_minor', 49,
	'version', 10876,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"Code/AMMO_12gauge.lua",
		"Code/AMMO_20x81.lua",
		"Code/AMMO_22LR.lua",
		"Code/AMMO_280British.lua",
		"Code/AMMO_300Blackout.lua",
		"Code/AMMO_300WinMag.lua",
		"Code/AMMO_303.lua",
		"Code/AMMO_308Win.lua",
		"Code/AMMO_30_60.lua",
		"Code/AMMO_32ACP.lua",
		"Code/AMMO_32HRMAG.lua",
		"Code/AMMO_338_Lapua_Magnum.lua",
		"Code/AMMO_357MAG.lua",
		"Code/AMMO_380ACP.lua",
		"Code/AMMO_38SP.lua",
		"Code/AMMO_408_ChayTac.lua",
		"Code/AMMO_40SW.lua",
		"Code/AMMO_44AMP.lua",
		"Code/AMMO_44CAL.lua",
		"Code/AMMO_44MAG.lua",
		"Code/AMMO_45ACP.lua",
		"Code/AMMO_4_6x30.lua",
		"Code/AMMO_4_7x33.lua",
		"Code/AMMO_50AE.lua",
		"Code/AMMO_50BMG.lua",
		"Code/AMMO_545x39.lua",
		"Code/AMMO_556x45.lua",
		"Code/AMMO_5_7x28.lua",
		"Code/AMMO_6_5Creedmoor.lua",
		"Code/AMMO_6_5Grendel.lua",
		"Code/AMMO_762x39.lua",
		"Code/AMMO_762x51.lua",
		"Code/AMMO_762x54.lua",
		"Code/AMMO_792x57.lua",
		"Code/AMMO_7_5x54.lua",
		"Code/AMMO_7_62x25.lua",
		"Code/AMMO_7_65x21.lua",
		"Code/AMMO_7_92x33.lua",
		"Code/AMMO_9x18.lua",
		"Code/AMMO_9x19.lua",
		"Code/AMMO_9x39.lua",
		"Code/TODO.lua",
		"CharacterEffect/shoot_move.lua",
		"CharacterEffect/shooting_stance.lua",
		"CharacterEffect/Marked.lua",
		"CharacterEffect/Revealed_R.lua",
		"CharacterEffect/wounded_Test.lua",
		"CharacterEffect/Rat_recoil.lua",
		"CharacterEffect/R_outofbreath.lua",
		"CharacterEffect/R_ReservedAP_stance.lua",
		"CharacterEffect/grunty_bonus.lua",
		"Code/_______init_globals.lua",
		"Code/UPDATE_Change components.lua",
		"Code/DESCRIPTION_HINTS_get.lua",
		"Code/T_ID_enforcement.lua",
		"Code/Assign_magsize.lua",
		"Code/OPTIONS_noise.lua",
		"Code/OnDataLoaded_CallCTH.lua",
		"Code/UnitDataDef_changes.lua",
		"Code/COMPATIBILITY_SmartOverwatch.lua",
		"Code/COMPATIBILITY_DescriptiveCTH.lua",
		"Code/TOC_ChangeEntity.lua",
		"Code/BOBBYRAY_category_pairs.lua",
		"Code/COMPONENT_weaponcomp_effects.lua",
		"Code/CONSTANTS_mod_options.lua",
		"Code/CONST_crit damage.lua",
		"Code/CTH_2weaponfire.lua",
		"Code/CTH_Setting.lua",
		"Code/CTH_unwield_weapon.lua",
		"Code/CTH_aim.lua",
		"Code/CTH_persistent_recoil.lua",
		"Code/CTH_autofire_recoil.lua",
		"Code/CTH_bipod.lua",
		"Code/CTH_cover_prone.lua",
		"Code/CTH_ow_cth.lua",
		"Code/CTH_ranged_melee_penal.lua",
		"Code/CTH_held_mg.lua",
		"Code/CTH_rungun.lua",
		"Code/CTH_scope.lua",
		"Code/CTH_pointblank.lua",
		"Code/CTH_hipfire_and_snapshot.lua",
		"Code/CTH_targeted_noburst.lua",
		"Code/CharEffectCompositeDef_function.lua",
		"Code/FUNCTION_disable_unpatched_shop.lua",
		"Code/FUNCTIONS_attributes.lua",
		"Code/FUNCTIONS_AI_custom.lua",
		"Code/FUNCTIONS_changeMagComponent.lua",
		"Code/FUNCTIONS_custom.lua",
		"Code/FUNCTIONS_dynamic_loot.lua",
		"Code/FUNCTION_Archetype_assign.lua",
		"Code/FUNCTIONS_Boltaction.lua",
		"Code/FUNCTIONS_recoil.lua",
		"Code/XTEMP_recoil.lua",
		"Code/FUNCTIONS_hipfire.lua",
		"Code/FX_inherit.lua",
		"Code/REACTIONS.lua",
		"Code/SOURCE_ Unit_EnterCombat.lua",
		"Code/SOURCE_AISignatureAction_MatchUnit.lua",
		"Code/SOURCE_GetAutoFireShots.lua",
		"Code/SOURCE_IModeCombatAreaAim_UpdateTarget.lua",
		"Code/SOURCE_IsOverwatchAction.lua",
		"Code/SOURCE_R_GetAreaAttackParams.lua",
		"Code/SOURCE_SwapWeapon.lua",
		"Code/SOURCE_bobbyray_adj.lua",
		"Code/SOURCE_recklessassault_tired.lua",
		"Code/SOURCE_shooting_stance_ANIMchangehook.lua",
		"Code/SOURCE_shooting_stance_BaseAimLevel.lua",
		"Code/SOURCE_shooting_stance__ANIM_idle.lua",
		"Code/SOURCE_shooting_stance_aimtarget.lua",
		"Code/SOURCE_shooting_stance_crosshair_ui.lua",
		"Code/SOURCE_shooting_stance_overwatch_function_n_attacks.lua",
		"Code/SOURCE_stealth_calc.lua",
		"Code/SOURCE_unitEnumUIactions.lua",
		"Code/SOURCE_unit_FirearmAttack.lua",
		"Code/SOURCE_FirearmGetAttackResults.lua",
		"Code/SOURCE_GetMaxAP.lua",
		"Code/SOURCE_CombatActionGetAttackableEnemies.lua",
		"Code/SOURCE_Firearm_GetItemStatusUI and QuickReloadButton.lua",
		"Code/SOURCE_BobbyRay_PickRandomWeightItems.lua",
		"Code/UNIT_REACTIONS_changes.lua",
		"Code/PATCH_call.lua",
		"Code/PATCH_weapons.lua",
		"Code/shooting_stance_aoesector_functions.lua",
		"Code/COMBAT_ACTIONS.lua",
		"Code/shooting_stance_functions.lua",
		"Code/shooting_stance_getap_extra.lua",
		"Code/shooting_stance_prepare_weapon_action.lua",
		"Code/subsonic_new_craft.lua",
		"Code/unit_properties.lua",
		"Code/weapon.properties.lua",
		"Code/weapon.properties.GETfunctions.lua",
		"InventoryItem/_79257_Tracer.lua",
		"InventoryItem/_54539_Tracer.lua",
		"InventoryItem/_76254R_Tracer.lua",
		"InventoryItem/_44CAL_Subsonic.lua",
		"InventoryItem/M14SAW_AUTO.lua",
	},
	'default_options', {
		AwareSight = "38 (rato's GBO default)",
		Extra_start_ap = "0 (default for Rato's GBO)",
		NightDetect = "-40 (Rato's Default)",
		NightSight = "-40 (Rato's Default)",
		UnawareSight = "18 (rato's GBO default)",
		ai_crit_multiplier = "100 (default for Rato's GBO)",
		ai_penal_setting = "100 (default for Rato's GBO)",
		aim_multiplier = "100 (default for Rato's GBO)",
		marks_multiplier = "100 (default for Rato's GBO)",
		max_aim_scaling = "100 (default for Rato's GBO)",
		max_targeted_scaling = "100 (default for Rato's GBO)",
		melee_multiplier = "100 (default for Rato's GBO)",
		min_aim_scaling = "10 (default for Rato's GBO)",
		min_targeted_scaling = "10 (default for Rato's GBO)",
		noise_setting = "100 (default for Rato's GBO)",
		ow_multiplier = "100 (default for Rato's GBO)",
		penalty_hipfire = "-40 (default for Rato's GBO)",
		penalty_snapshot = "-30 (default for Rato's GBO)",
		r_round_mul = true,
		recoil_persistent_aim_effect = "100",
		recoil_persistent_setting = "100 (default for Rato's GBO)",
		recoil_setting = "100 (default for Rato's GBO)",
		targeted_multiplier = "100 (default for Rato's GBO)",
	},
	'has_data', true,
	'saved', 1716864725,
	'code_hash', -6573609328108780356,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "Caliber",
			'Id', "762x54R",
			'ClassDisplayName', "Caliber mod",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Caliber",
			'Id', "545x39",
			'ClassDisplayName', "Caliber mod",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Caliber",
			'Id', "792x57",
			'ClassDisplayName', "Caliber mod",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "shoot_move",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "shooting_stance",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Marked",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Revealed_R",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "wounded_Test",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Rat_recoil",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "R_outofbreath",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "R_ReservedAP_stance",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "grunty_bonus",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "GrazingHitDamage",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_BurstFirePenalty",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_AutoFirePenalty",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_LongBurstPenalty",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_HeldLongBurstPenalty",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_HeldCumbersomePenalty",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_HipFirePenalty",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_SnapshotPenalty",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_AimMul",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_OWMul",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_AI_critmul",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_TargetedMul",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_MaxAimScaling",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_MaxTargetedScaling",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_RecoilP",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_Recoil",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_MinAimScaling",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_MinTargetedScaling",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_MeleeMul",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_MarksMul",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_AIReduc",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_ExtraAP",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "AwareSightRange",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "UnawareSightRange",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "RainAimingMultiplier",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "PointBlankRange",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "MGFreeInterruptAttacks",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "R_Round_Mul",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "AP_792_craft",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "HP_792_craft",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "TRACER_792_craft",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "Match_792_craft",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "BASIC_792_craft",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "BASIC_792_convert",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_556_HP",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_556_Basic",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_556_Match",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_556_Tracer",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_556_AP",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_50BMG_Basic",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_50BMG_HE",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_50BMG_Incendiary",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_50BMG_SLAP",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_762NATO_HP",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_762NATO_Basic",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_762NATO_Match",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_762NATO_Tracer",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_762NATO_AP",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_79257_Tracer",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_762WP_HP",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_762WP_Basic",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_762WP_Match",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_762WP_AP",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_762WP_Tracer",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_54539_Tracer",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_76254R_Tracer",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_12gauge_Flechette",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_12gauge_Breacher",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_12gauge_Buckshot",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_12gauge_Saltshot",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_44CAL_Match",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_44CAL_HP",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_44CAL_Shock",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_44CAL_Subsonic",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_44CAL_AP",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_44CAL_Basic",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_9mm_Shock",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_9mm_AP",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_9mm_Basic",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_9mm_HP",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_9mm_Match",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_9mm_Tracer",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_9mm_Subsonic",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "M14SAW_AUTO",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "TheMajor",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "ammo_rand_762_54R",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "ammo_rand_545",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "RebelSoldier",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "RebelGunner",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Ak_SKS",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "RebelSniper",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "ThugGunner",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Chimurenga",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "ThugSniper_Stronger",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Bunker_MG42_ammo",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Bunker_SpecialAmmo",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "FlagHill_Beach_Gun",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Outlook_Chest_Up_Tower",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Fortress_Tower",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Bunker_MP40_add_ammo",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Kalyna",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Gus",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Scope",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Scully",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "HIll_StockGalil_01",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Barrel50BMG_DesertEagle",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LionRoar_compensator",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Internal_plus_burstshot",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MuzzleBooster",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MuzzleBooster_Glock18",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Suppressor",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ImprovisedSuppressor",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LROpticsAdvanced",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LROptics",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ScopeCOG",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ScopeCOGQuick",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ReflexSight",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ReflexSightAdvanced",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "_ReflexSIghtVigilance",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ThermalScope",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AUGScope_Default",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G36_SCOPE",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SCOPE_G36_2",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ReflexSightAdvanced_Glock",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "WideScope",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "barrel_confidante",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelLongShotgun",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Auto5_Long_LMag",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Auto5_Long_NMag",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Auto5_Short_NMag",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShort_Winchester",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShortShotgun_Benelli",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShort",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShort_handgun",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShort_Light_handgun",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelLight_handgun",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "_master_BarrelShort",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShort_Light",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelLight",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "StockLight",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShortImproved",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShortImproved_handgun",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "StockNo",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShortShotgun",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "StockFolded",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "StockLight_AR_BurstOnly",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "StockHeavy_AR_BurstOnly",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VerticalGrip",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VerticalGrip_aug",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Bipod",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Bipod_m82",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Bipod_Under",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "stock_uzi",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Bipod_MG42",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AK47_VerticalGrip",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagNormal",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine_2",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine_3",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine_4",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine_5",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine_6",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine_7",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine_8",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine_9",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine_10",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine_11",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLargeFine_12",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge_2",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelLong_handgun",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge_3",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge_4",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge_5",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge_6",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge_7",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge_8",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge_9",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge_10",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge_11",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge_12",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "_RatMaster_MagLarge",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagQuick",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "R_MagQuickLarge",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagNormalFine",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "long_barrel_light_handgun",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LROptics_DragunovDefault",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelLongImproved_handgun",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "bullup",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelLong",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelLong_jaggerMeister",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelLong_AUG",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "long_barrel_AUG_light",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "long_barrel_light",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelLongImproved",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelLongImproved_AUG",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VerticalGrip_M14",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VerticalGrip_M16",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VerticalGrip_Commando",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelHeavyLong",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Bolt_action",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "lever_action",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Bolt_action_scout",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "single_action",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "single_action_tex",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "double_action",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SADA_action",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "m14_component_recoil",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "StockHeavy",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "StockNormal",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "foldable_StockNormal",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelNormal",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "UVDot",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LaserDot",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FlashlightDot",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "stealth_ironsight_confidante",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Flashlight",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "GrenadeLauncher_M14",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "TacGrip_M14",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "winni_to54r",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FullChoke",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "DuckbillChoke",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Compensator",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "rpk_to762wp",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "browning_bipod",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FNFAL_Handguard",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "handgun_freeswap",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AKSU_VerticalGrip",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RPK74_VerticalGrip",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Compensator_Glock",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ImprovedIronsight",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "StockBump",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelHeavy",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AUGCompensator_01",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AUGCompensator_03",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "GrenadeLauncher",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AK47_Launcher",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "GrenadeLauncher_Commando",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "GrenadeLauncher_M16A1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "GrenadeLauncher_AUG",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PSG_DefaultScope",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "UVDot_Anaconda",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LaserDot_PSG_M1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "UVDot_PSG_M1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LaserDot_Anaconda",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LaserDot_aa12",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "UVDot_aa12",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShort_AUG",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BarrelShortImproved_AUG",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M16_Handguard",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "TacGrip",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AK47_TacGrip",
			'ClassDisplayName', "Weapon component",
		}),
	},
	'steam_id', "3021320057",
	'TagBalancing&Difficulty', true,
	'TagCombat&AI', true,
	'TagWeapons&Items', true,
})