-- ========== GENERATED BY CraftOperationsRecipeDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "TNT",
			'amount', 3,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "HE_Grenade_1",
		'amount', 5,
	}),
	group = "Explosives",
	id = "HE_Grenade_1",
})

