-- ========== GENERATED BY CraftOperationsRecipeDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_54539_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_54539_AP",
		'amount', 30,
	}),
	group = "Ammo",
	id = "54539_AP_Craft",
	
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_54539_Basic",
		'amount', 30,
	}),
	group = "Ammo",
	id = "545x39_Basic_Craft",
	
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_54539_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_54539_HP",
		'amount', 30,
	}),
	group = "Ammo",
	id = "545x39_HP_Craft",
	
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_54539_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_54539_Match",
		'amount', 30,
	}),
	group = "Ammo",
	id = "545x39_Match_Craft",
	
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_54539_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_54539_Tracer",
		'amount', 30,
	}),
	group = "Ammo",
	id = "545x39_Tracer_Craft",
	
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_76254R_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_76254R_AP",
		'amount', 30,
	}),
	group = "Ammo",
	id = "762x54R_AP_Craft",

})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_76254R_Basic",
		'amount', 30,
	}),
	group = "Ammo",
	id = "762x54R_Basic_Craft",

})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_76254R_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_76254R_HP",
		'amount', 30,
	}),
	group = "Ammo",
	id = "62x54R_HP_Craft",

})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_76254R_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_76254R_Match",
		'amount', 30,
	}),
	group = "Ammo",
	id = "762x54R_Match_Craft",

})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_76254R_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_76254R_Tracer",
		'amount', 30,
	}),
	group = "Ammo",
	id = "762x54R_Tracer_Craft",

})
