-- ========== GENERATED BY CraftOperationsRecipeDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 10,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 8,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_44CAL_Basic",
			'amount', 24,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_44CAL_Subsonic",
		'amount', 24,
	}),
	group = "Ammo",
	id = "44CAL_Subsonic",

})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "_556_Basic",
			'amount', 30,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_556_Subsonic",
		'amount', 30,
	}),
	group = "Ammo",
	id = "556_Subsonic",

})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_762NATO_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_762NATO_Subsonic",
		'amount', 30,
	}),
	group = "Ammo",
	id = "762NATO_Subsonic",

})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_762WP_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_762WP_Subsonic",
		'amount', 30,
	}),
	group = "Ammo",
	id = "762WP_Subsonic",

})




