UndefineClass('AA12')
DefineClass.AA12 = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 12ga ----- SHOTGUN",
	object_class = "Shotgun",
	ScrapParts = 12,
	RepairCost = 50,
	Reliability = 80,
	Icon = "UI/Icons/Weapons/AA12",
	DisplayName = T(966111040192, --[[ModItemInventoryItemCompositeDef AA12 DisplayName]] "AA12"),
	DisplayNamePlural = T(575804327511, --[[ModItemInventoryItemCompositeDef AA12 DisplayNamePlural]] "AA12s"),
	Description = T(838511597425, --[[ModItemInventoryItemCompositeDef AA12 Description]] "Firing from an open bolt, the AA12 has more similarity with some machine guns than with other shotguns. Boasting reduced recoil for a 12-gauge round, it is made for sustained fire."),
	AdditionalHint = T(141818519778, --[[ModItemInventoryItemCompositeDef AA12 AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Special firing mode: Buckshot Burst"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 13200,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 40,
	CategoryPair = "Shotguns",
	Caliber = "12gauge",
	Damage = 25,
	ObjDamageMod = 150,
	MagazineSize = 8,
	WeaponRange = 8,
	PointBlankBonus = 1,
	OverwatchAngle = 1001,
	BuckshotConeAngle = 480,
	BuckshotFalloffDamage = 50,
	Noise = 25,
	HandSlot = "TwoHanded",
	Entity = "Weapon_AA12",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelLongShotgun",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge_6",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ReflexSightAdvanced",
				"ReflexSight",
				"ScopeCOGQuick",
				"_ReflexSIghtVigilance",
				"ImprovedIronsight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight_aa12",
				"LaserDot_aa12",
				"FlashlightDot_aa12",
				"UVDot_aa12",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Suppressor",
				"Compensator",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BuckshotBurst",
		"Buckshot",
		"CancelShotCone",
	},
	ShootAP = 3000,
	ReloadAP = 3000,
	APStance = 4,
	PBbonus_base = 1,
	wep_base_recoil_mul = 97,
	wep_base_hip_mul = 97,
	wep_base_snapshot_mul = 107,
	weigth_held_mul = 133,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "Auto",
	recoil_mechanism = "Gas_Operated",
	rat_weigth = 4700,
	rat_barrel_len = 460,
}

