UndefineClass('AKSU')
DefineClass.AKSU = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 5.45 ----- SMG",
	object_class = "SubmachineGun",
	ScrapParts = 10,
	RepairCost = 50,
	Reliability = 80,
	Icon = "UI/Icons/Weapons/AKSU",
	DisplayName = T(464644421151, --[[ModItemInventoryItemCompositeDef AKSU DisplayName]] "AK-SU"),
	DisplayNamePlural = T(365680292811, --[[ModItemInventoryItemCompositeDef AKSU DisplayNamePlural]] "AK-SUs"),
	Description = T(745934809760, --[[ModItemInventoryItemCompositeDef AKSU Description]] "Short versions of the AK-74 intended for Spec Ops and vehicle crew personal defense. It needed a custom gas block and muzzle booster to work properly. Americans call it Krinkov but Russians have a more intimate nickname - Ksyukha or sometimes Suchka. And yes, there is a thigh holster for it. "),
	AdditionalHint = T(326130558343, --[[ModItemInventoryItemCompositeDef AKSU AdditionalHint]] "<description_hints>"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 7500,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 40,
	CategoryPair = "SubmachineGuns",
	Caliber = "545x39",
	Damage = 21,
	AimAccuracy = 3,
	MagazineSize = 30,
	PointBlankBonus = 1,
	OverwatchAngle = 1448,
	HandSlot = "TwoHanded",
	Entity = "Weapon_AKS74U",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'Modifiable', false,
			'AvailableComponents', {
				"BarrelNormal",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"AKSU_Hanguard_Basic",
				"AKSU_VerticalGrip",
			},
			'DefaultComponent', "AKSU_Hanguard_Basic",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
				"MagLarge",
				"MagQuick",
				"MagLargeFine",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
				"WideScope",
				"_ReflexSIghtVigilance",
				"LROptics_DragunovDefault",
				"ImprovedIronsight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"Compensator",
				"MuzzleBooster",
				"Suppressor",
				"ImprovisedSuppressor",
			},
			'DefaultComponent', "MuzzleBooster",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLight",
			},
			'DefaultComponent', "StockLight",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	ShootAP = 3000,
	ReloadAP = 3000,
	PBbonus_base = 9,
	wep_base_recoil_mul = 119,
	placeholder_recoil = 109,
	wep_base_hip_mul = 111,
	wep_base_snapshot_mul = 84,
	weigth_held_mul = 120,
	is_vanilla_firearm = true,
	Rat_cycling = "Auto",
	recoil_mechanism = "Gas_Operated",
	rat_weigth = 2900,
	rat_barrel_len = 210,
}

