UndefineClass('AR15')
DefineClass.AR15 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 5.56  ----- ASSAULT",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	Reliability = 80,
	Icon = "UI/Icons/Weapons/AR15",
	DisplayName = T(685948268126, --[[ModItemInventoryItemCompositeDef AR15 DisplayName]] "AR-15"),
	DisplayNamePlural = T(447353788089, --[[ModItemInventoryItemCompositeDef AR15 DisplayNamePlural]] "AR-15s"),
	Description = T(638006397413, --[[ModItemInventoryItemCompositeDef AR15 Description]] "Created to ensure the highest constitutional rights of self-defense and the possibility to bear a weapon that's easy as hell to convert to a fully-automatic one because a law-abiding citizen always needs one."),
	AdditionalHint = T(145852997392, --[[ModItemInventoryItemCompositeDef AR15 AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Only semi-auto with standard stocks"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 8600,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 90,
	CategoryPair = "AssaultRifles",
	Caliber = "556",
	Damage = 24,
	AimAccuracy = 5,
	CritChanceScaled = 30,
	MagazineSize = 30,
	WeaponRange = 26,
	PointBlankBonus = 1,
	OverwatchAngle = 1130,
	HandSlot = "TwoHanded",
	Entity = "Weapon_AR15",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"ScopeCOG",
				"LROptics",
				"LROpticsAdvanced",
				"ThermalScope",
				"ReflexSight",
				"DefaultIronsight_AR15",
				"ImprovedIronsight_AR15",
				"WideScope",
				"_ReflexSIghtVigilance",
				"ReflexSightAdvanced",
			},
			'DefaultComponent', "DefaultIronsight_AR15",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
				"MagLarge",
				"MagLargeFine",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelShort",
				"BarrelShortImproved",
				"BarrelLongImproved",
				"BarrelLight",
				"long_barrel_light",
				"BarrelShort_Light",
				"BarrelHeavyLong",
				"BarrelLong",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy_AR_BurstOnly",
				"StockLight_AR_BurstOnly",
				"StockBump",
			},
			'DefaultComponent', "StockHeavy_AR_BurstOnly",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"GrenadeLauncher",
				"VerticalGrip",
				"TacGrip",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"ImprovisedSuppressor",
				"Suppressor",
				"MuzzleBooster",
			},
			'DefaultComponent', "Compensator",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"BurstFire",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	APStance = 4,
	PBbonus_base = 2,
	wep_base_recoil_mul = 101,
	wep_base_hip_mul = 98,
	wep_base_snapshot_mul = 101,
	weigth_held_mul = 121,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "SemiAuto",
	recoil_mechanism = "Gas_Operated",
	rat_weigth = 3000,
	rat_barrel_len = 450,
}

