UndefineClass('Auto5')
DefineClass.Auto5 = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 12ga ----- SHOTGUN",
	object_class = "Shotgun",
	ScrapParts = 10,
	RepairCost = 50,
	Reliability = 20,
	Icon = "UI/Icons/Weapons/Browning Auto-5",
	DisplayName = T(290360269467, --[[ModItemInventoryItemCompositeDef Auto5 DisplayName]] "Auto-5"),
	DisplayNamePlural = T(659232890996, --[[ModItemInventoryItemCompositeDef Auto5 DisplayNamePlural]] "Auto-5s"),
	Description = T(533067727452, --[[ModItemInventoryItemCompositeDef Auto5 Description]] "First mass produced semi-automatic shotgun in the world. Turned out it was one hell of a good gun for jungle close-quarter firefights. "),
	AdditionalHint = T(413545464036, --[[ModItemInventoryItemCompositeDef Auto5 AdditionalHint]] "<description_hints>"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 1700,
	CanAppearInShop = true,
	RestockWeight = 50,
	CategoryPair = "Shotguns",
	CanAppearStandard = false,
	Caliber = "12gauge",
	Damage = 27,
	ObjDamageMod = 150,
	AimAccuracy = 1,
	MagazineSize = 4,
	WeaponRange = 10,
	PointBlankBonus = 1,
	OverwatchAngle = 959,
	BuckshotConeAngle = 720,
	BuckshotFalloffDamage = 50,
	Noise = 25,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Auto5",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"DuckbillChoke",
				"FullChoke",
				"Compensator",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"Auto5_Basic_LMag",
				"Auto5_Basic_NMag",
				"Auto5_Long_LMag",
				"Auto5_Long_NMag",
				"Auto5_Short_NMag",
			},
			'DefaultComponent', "Auto5_Basic_NMag",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"Buckshot",
		"CancelShotCone",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	PBbonus_base = -1,
	wep_base_recoil_mul = 98,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "SemiAuto",
	recoil_mechanism = "Recoil_Operated",
}

