UndefineClass('Bereta92')
DefineClass.Bereta92 = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 9mm ----- PISTOL",
	object_class = "Pistol",
	msg_reactions = {},
	ScrapParts = 6,
	RepairCost = 70,
	Reliability = 70,
	Icon = "UI/Icons/Weapons/Beretta92F",
	DisplayName = T(830527158934, --[[ModItemInventoryItemCompositeDef Bereta92 DisplayName]] "Beretta 92F"),
	DisplayNamePlural = T(994487335427, --[[ModItemInventoryItemCompositeDef Bereta92 DisplayNamePlural]] "Beretta 92Fs"),
	Description = T(902228765263, --[[ModItemInventoryItemCompositeDef Bereta92 Description]] "The weapon that replaced the iconic 1911. Tough act to follow but the slick Italian manages to impress. "),
	AdditionalHint = T(612920982302, --[[ModItemInventoryItemCompositeDef Bereta92 AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Swapping to this weapon is free, as long it is not dual-wielded"),
	UnitStat = "Marksmanship",
	Cost = 1200,
	CanAppearInShop = true,
	RestockWeight = 70,
	CategoryPair = "Handguns",
	Caliber = "9mm",
	Damage = 17,
	AimAccuracy = 3,
	CritChanceScaled = 30,
	MagazineSize = 15,
	WeaponRange = 16,
	PointBlankBonus = 1,
	OverwatchAngle = 2209,
	Noise = 18,
	Entity = "Weapon_Beretta92F",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ReflexSight",
				"_ReflexSIghtVigilance",
				"ReflexSightAdvanced_Glock",
				"ImprovedIronsight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagLarge",
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong_handgun",
				"BarrelNormal",
				"long_barrel_light_handgun",
				"BarrelLight",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	APStance = 1,
	PBbonus_base = 12,
	wep_base_recoil_mul = 115,
	wep_base_hip_mul = 116,
	wep_base_snapshot_mul = 71,
	weigth_held_mul = 106,
	Rat_swap_ap = 1,
	is_vanilla_firearm = true,
	Rat_cycling = "SemiAuto",
	recoil_mechanism = "Short_Recoil",
	rat_weigth = 950,
	rat_barrel_len = 120,
}

