UndefineClass('ColtPeacemaker')
DefineClass.ColtPeacemaker = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ .44 cal ----- REVOLVER",
	object_class = "Revolver",
	ScrapParts = 6,
	RepairCost = 30,
	Reliability = 85,
	Icon = "UI/Icons/Weapons/Colt Peacemaker",
	DisplayName = T(843417343545, --[[ModItemInventoryItemCompositeDef ColtPeacemaker DisplayName]] "Peacemaker"),
	DisplayNamePlural = T(912936866898, --[[ModItemInventoryItemCompositeDef ColtPeacemaker DisplayNamePlural]] "Peacemakers"),
	Description = T(480991138124, --[[ModItemInventoryItemCompositeDef ColtPeacemaker Description]] "Single action revolver designed for the US army. Don't forget to carry it with one empty under the hammer unless you want a hole in your foot."),
	AdditionalHint = T(626602087367, --[[ModItemInventoryItemCompositeDef ColtPeacemaker AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Single action\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Swapping to this weapon is free, as long it is not dual-wielded"),
	UnitStat = "Marksmanship",
	Cost = 950,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	Caliber = "44CAL",
	Damage = 21,
	AimAccuracy = 5,
	CritChanceScaled = 20,
	MagazineSize = 6,
	WeaponRange = 18,
	PointBlankBonus = 1,
	OverwatchAngle = 2162,
	Noise = 18,
	Entity = "Weapon_Colt",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong_handgun",
				"BarrelNormal",
				"BarrelShort_handgun",
				"BarrelLight",
				"long_barrel_light_handgun",
				"BarrelShort_Light_handgun",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Trigger",
			'Modifiable', false,
			'AvailableComponents', {
				"single_action",
			},
			'DefaultComponent', "single_action",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	APStance = 1,
	PBbonus_base = 11,
	wep_base_recoil_mul = 114,
	wep_base_hip_mul = 113,
	wep_base_snapshot_mul = 73,
	weigth_held_mul = 105,
	Rat_swap_ap = 1,
	is_vanilla_firearm = true,
	Rat_cycling = "SingleAction",
	recoil_mechanism = "Revolver",
	rat_weigth = 720,
	rat_barrel_len = 160,
}

