UndefineClass('ColtAnaconda')
DefineClass.ColtAnaconda = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ .44 cal ----- REVOLVER",
	object_class = "Revolver",
	ScrapParts = 8,
	RepairCost = 30,
	Reliability = 85,
	Icon = "UI/Icons/Weapons/Anaconda",
	DisplayName = T(594866700386, --[[ModItemInventoryItemCompositeDef ColtAnaconda DisplayName]] "Anaconda"),
	DisplayNamePlural = T(424940015770, --[[ModItemInventoryItemCompositeDef ColtAnaconda DisplayNamePlural]] "Anacondas"),
	Description = T(951911138385, --[[ModItemInventoryItemCompositeDef ColtAnaconda Description]] "Double-action revolver with a swing out cylinder. High reliability and stopping power shot after shot. "),
	AdditionalHint = T(879153829726, --[[ModItemInventoryItemCompositeDef ColtAnaconda AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Double action\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Swapping to this weapon is free, as long it is not dual-wielded"),
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 4500,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 70,
	CategoryPair = "Handguns",
	Caliber = "44CAL",
	Damage = 22,
	AimAccuracy = 5,
	CritChanceScaled = 30,
	MagazineSize = 6,
	WeaponRange = 18,
	PointBlankBonus = 1,
	OverwatchAngle = 2118,
	Noise = 18,
	Entity = "Weapon_ColtAnaconda44",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong_handgun",
				"BarrelNormal",
				"BarrelShort_handgun",
				"BarrelLight",
				"long_barrel_light_handgun",
				"BarrelShort_Light_handgun",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"BaseIronsight_Anaconda",
				"ImprovedIronsight",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"LaserDot_Anaconda",
				"FlashlightDot_Anaconda",
				"UVDot_Anaconda",
				"_ReflexSIghtVigilance",
				"WideScope",
			},
			'DefaultComponent', "BaseIronsight_Anaconda",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Trigger",
			'Modifiable', false,
			'AvailableComponents', {
				"SADA_action",
			},
			'DefaultComponent', "SADA_action",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	APStance = 1,
	PBbonus_base = 12,
	wep_base_recoil_mul = 114,
	wep_base_hip_mul = 114,
	wep_base_snapshot_mul = 75,
	weigth_held_mul = 110,
	Rat_swap_ap = 1,
	is_vanilla_firearm = true,
	Rat_cycling = "DoubleAction",
	recoil_mechanism = "Revolver",
	rat_weigth = 1400,
	rat_barrel_len = 150,
}

