UndefineClass('ConcussiveGrenade_RAT_1')
DefineClass.ConcussiveGrenade_RAT_1 = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/ConcussiveGrenade",
	ItemType = "Grenade",
	DisplayName = T(335146581022, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade_RAT_1 DisplayName]] "Flashbang"),
	DisplayNamePlural = T(758959916840, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade_RAT_1 DisplayNamePlural]] "Flashbangs"),
	AdditionalHint = T(822477657158, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade_RAT_1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Suppressed</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Dazed</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cancel readied attacks\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very loud. That's the point of this grenade"),
	UnitStat = "Explosives",
	Cost = 800,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 25,
	CategoryPair = "Grenade",
	MinMishapChance = 30,
	MaxMishapChance = 90,
	MinMishapRange = 0,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	CenterAppliedEffects = {
		"Suppressed",
		"dazed_flashbang",
		"cancel_shot_flashbang",
	},
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	AreaAppliedEffects = {
		"Suppressed",
		"dazed_flashbang",
		"cancel_shot_flashbang",
	},
	PenetrationClass = 1,
	BurnGround = false,
	BaseDamage = 0,
	Scatter = 4,
	AttackAP = 4000,
	InaccurateMaxOffset = 4000,
	Entity = "Weapon_StunGrenadeM84",
	ActionIcon = "UI/Icons/Hud/concussive_grenade",
}

