UndefineClass('DesertEagle')
DefineClass.DesertEagle = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ .44 cal ----- PISTOL",
	object_class = "Pistol",
	ScrapParts = 10,
	RepairCost = 70,
	Icon = "UI/Icons/Weapons/DesertEagle",
	DisplayName = T(678627018253, --[[ModItemInventoryItemCompositeDef DesertEagle DisplayName]] "Desert Eagle"),
	DisplayNamePlural = T(174878234604, --[[ModItemInventoryItemCompositeDef DesertEagle DisplayNamePlural]] "Desert Eagles"),
	Description = T(952249117115, --[[ModItemInventoryItemCompositeDef DesertEagle Description]] "Everybody knows the Desert Eagle as a .50 caliber hand cannon but the .44 barrel can make it much more practical and affordable to shoot. "),
	AdditionalHint = T(467653092333, --[[ModItemInventoryItemCompositeDef DesertEagle AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Swapping to this weapon is free, as long it is not dual-wielded"),
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 6000,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 40,
	CategoryPair = "Handguns",
	Caliber = "44CAL",
	Damage = 23,
	ObjDamageMod = 200,
	AimAccuracy = 4,
	CritChanceScaled = 20,
	MagazineSize = 15,
	PointBlankBonus = 1,
	OverwatchAngle = 1936,
	Entity = "Weapon_DesertEagle",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ReflexSight",
				"ReflexSightAdvanced",
				"ImprovedIronsight",
				"_ReflexSIghtVigilance",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong_handgun",
				"BarrelNormal",
				"Barrel50BMG_DesertEagle",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Suppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"FlashlightDot",
				"Flashlight",
				"LaserDot",
				"UVDot",
			},
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	APStance = 1,
	PBbonus_base = 11,
	wep_base_recoil_mul = 112,
	wep_base_hip_mul = 114,
	wep_base_snapshot_mul = 77,
	weigth_held_mul = 115,
	Rat_swap_ap = 1,
	is_vanilla_firearm = true,
	Rat_cycling = "SemiAuto",
	recoil_mechanism = "Short_Recoil",
	rat_weigth = 2100,
	rat_barrel_len = 150,
}

