UndefineClass('DoubleBarrelShotgun')
DefineClass.DoubleBarrelShotgun = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 12ga ----- SHOTGUN",
	object_class = "Shotgun",
	ScrapParts = 8,
	RepairCost = 50,
	Reliability = 50,
	Icon = "UI/Icons/Weapons/Double-barrelled Shotgun",
	DisplayName = T(280093901776, --[[ModItemInventoryItemCompositeDef DoubleBarrelShotgun DisplayName]] "Double-Barrel"),
	DisplayNamePlural = T(981757390798, --[[ModItemInventoryItemCompositeDef DoubleBarrelShotgun DisplayNamePlural]] "Double-Barrels"),
	Description = T(499880748140, --[[ModItemInventoryItemCompositeDef DoubleBarrelShotgun Description]] "A simple hunting weapon. Fancier combat shotguns can shoot semi and fully automatic but only the double-barrel can shoot two shells at once. "),
	AdditionalHint = T(150578847961, --[[ModItemInventoryItemCompositeDef DoubleBarrelShotgun AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Special firing mode: Double Barrel"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 1100,
	CanAppearInShop = true,
	RestockWeight = 120,
	CategoryPair = "Shotguns",
	Caliber = "12gauge",
	Damage = 25,
	ObjDamageMod = 150,
	AimAccuracy = 1,
	MagazineSize = 2,
	WeaponRange = 8,
	PointBlankBonus = 1,
	OverwatchAngle = 901,
	BuckshotConeAngle = 600,
	BuckshotFalloffDamage = 50,
	Noise = 25,
	HandSlot = "TwoHanded",
	Entity = "Weapon_DBShotgun",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLongShotgun",
				"BarrelNormal",
				"BarrelShortShotgun",
			},
			'DefaultComponent', "BarrelNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"Buckshot",
		"DoubleBarrel",
		"CancelShotCone",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	PBbonus_base = -3,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "BreakAction",
	recoil_mechanism = "Break_Action",
}

