UndefineClass('DragunovSVD')
DefineClass.DragunovSVD = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 7.62x54R ----- SNIPER",
	object_class = "SniperRifle",
	ScrapParts = 14,
	Reliability = 50,
	Icon = "UI/Icons/Weapons/Dragunov",
	DisplayName = T(893108258287, --[[ModItemInventoryItemCompositeDef DragunovSVD DisplayName]] "Dragunov"),
	DisplayNamePlural = T(763187888643, --[[ModItemInventoryItemCompositeDef DragunovSVD DisplayNamePlural]] "Dragunovs"),
	Description = T(223744696911, --[[ModItemInventoryItemCompositeDef DragunovSVD Description]] "Not what it seems at first glance. On the outside it looks like an AK but actually uses a short stroke gas piston system that reduces the recoil and allows for better follow up shots. It is more of a close support designated marksman's rifle than a sniper one. "),
	AdditionalHint = T(715363343098, --[[ModItemInventoryItemCompositeDef DragunovSVD AdditionalHint]] "<description_hints>"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 12400,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 2,
	RestockWeight = 60,
	CategoryPair = "Rifles",
	Caliber = "762x54R",
	Damage = 32,
	AimAccuracy = 7,
	CritChanceScaled = 20,
	MagazineSize = 10,
	WeaponRange = 30,
	PointBlankBonus = 1,
	OverwatchAngle = 820,
	Noise = 22,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Dragunov",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockLight",
				"StockNormal",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"LROptics_DragunovDefault",
				"ReflexSight",
				"ScopeCOG",
				"ThermalScope",
				"LROpticsAdvanced",
				"ReflexSightAdvanced",
				"ScopeCOGQuick",
				"_ReflexSIghtVigilance",
				"WideScope",
				"PSG_DefaultScope",
				"LROptics",
			},
			'DefaultComponent', "LROptics_DragunovDefault",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
			},
			'DefaultComponent', "Compensator",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Both",
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	APStance = 5,
	default_long_barrel = true,
	PBbonus_base = -2,
	wep_base_recoil_mul = 92,
	wep_base_hip_mul = 89,
	wep_base_snapshot_mul = 117,
	weigth_held_mul = 132,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "SemiAuto",
	recoil_mechanism = "Gas_Operated",
	rat_weigth = 4500,
	rat_barrel_len = 610,
}

