UndefineClass('FAMAS')
DefineClass.FAMAS = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 5.56  ----- ASSAULT",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	Reliability = 70,
	Icon = "UI/Icons/Weapons/FAMAS",
	DisplayName = T(999707929261, --[[ModItemInventoryItemCompositeDef FAMAS DisplayName]] "FAMAS"),
	DisplayNamePlural = T(378553886065, --[[ModItemInventoryItemCompositeDef FAMAS DisplayNamePlural]] "FAMAS's"),
	Description = T(358558386519, --[[ModItemInventoryItemCompositeDef FAMAS Description]] "Bullpup design with utility and ergonomics in mind. The magazines were designed to be single-use and disposable. But no design survives contact with reality - soldiers started reusing them and running into all sorts of problems. A durable mag was later introduced. "),
	AdditionalHint = T(423566125417, --[[ModItemInventoryItemCompositeDef FAMAS AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased Reload cost"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 5200,
	CanAppearInShop = true,
	RestockWeight = 80,
	CategoryPair = "AssaultRifles",
	Caliber = "556",
	Damage = 22,
	AimAccuracy = 4,
	MagazineSize = 25,
	WeaponRange = 24,
	PointBlankBonus = 1,
	OverwatchAngle = 1051,
	Noise = 18,
	HandSlot = "TwoHanded",
	Entity = "Weapon_FAMAS",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"VerticalGrip",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ScopeCOGQuick",
				"ScopeCOG",
				"ThermalScope",
				"_ReflexSIghtVigilance",
				"WideScope",
				"ImprovedIronsight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
				"ImprovisedSuppressor",
			},
			'DefaultComponent', "Compensator",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "General",
			'Modifiable', false,
			'AvailableComponents', {
				"bullup",
			},
			'DefaultComponent', "bullup",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	PBbonus_base = 0,
	wep_base_recoil_mul = 97,
	burst_recoil_delta = 90,
	burst_selective = true,
	wep_base_hip_mul = 94,
	wep_base_snapshot_mul = 108,
	weigth_held_mul = 127,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "Auto",
	recoil_mechanism = "Gas_Operated",
	rat_weigth = 3900,
	rat_barrel_len = 510,
}

