UndefineClass('FNMinimi')
DefineClass.FNMinimi = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 5.56  ----- MG",
	object_class = "MachineGun",
	ScrapParts = 16,
	RepairCost = 120,
	Reliability = 85,
	Icon = "UI/Icons/Weapons/Minimi",
	DisplayName = T(881677033179, --[[ModItemInventoryItemCompositeDef FNMinimi DisplayName]] "Minimi"),
	DisplayNamePlural = T(516358751595, --[[ModItemInventoryItemCompositeDef FNMinimi DisplayNamePlural]] "Minimis"),
	Description = T(851064745482, --[[ModItemInventoryItemCompositeDef FNMinimi Description]] "The 5.56 NATO Minimi is meant to provide squad-level fire support. It does so well that it was adopted by the US military and most people know it as the M249 squad automatic weapon. There is also a Minimi variant firing 7.62 NATO rounds."),
	AdditionalHint = T(616169182043, --[[ModItemInventoryItemCompositeDef FNMinimi AdditionalHint]] "<description_hints>"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 18700,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 25,
	CategoryPair = "MachineGuns",
	Caliber = "556",
	Damage = 23,
	AimAccuracy = 3,
	MagazineSize = 100,
	WeaponRange = 34,
	PointBlankBonus = 1,
	OverwatchAngle = 781,
	Noise = 22,
	HandSlot = "TwoHanded",
	Entity = "Weapon_FNMinimi",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong",
				"BarrelLongImproved",
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelShort",
				"BarrelShortImproved",
				"long_barrel_light",
				"BarrelLight",
				"BarrelShort_Light",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockNormal",
				"StockLight",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovedIronsight",
				"ReflexSight",
				"ReflexSightAdvanced",
				"LROptics",
				"LROpticsAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
				"WideScope",
				"_ReflexSIghtVigilance",
				"PSG_DefaultScope",
				"UVDot_Anaconda",
				"LaserDot_Anaconda",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge_12",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	APStance = 5,
	PBbonus_base = 0,
	wep_base_recoil_mul = 91,
	wep_base_hip_mul = 97,
	wep_base_snapshot_mul = 119,
	weigth_held_mul = 156,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "Auto",
	recoil_mechanism = "Gas_Operated",
	rat_weigth = 7900,
	rat_barrel_len = 460,
}

