UndefineClass('G36')
DefineClass.G36 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 5.56  ----- ASSAULT",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	Reliability = 75,
	Icon = "UI/Icons/Weapons/G36",
	DisplayName = T(288968482053, --[[ModItemInventoryItemCompositeDef G36 DisplayName]] "G36"),
	DisplayNamePlural = T(545295775779, --[[ModItemInventoryItemCompositeDef G36 DisplayNamePlural]] "G36s"),
	Description = T(983108943373, --[[ModItemInventoryItemCompositeDef G36 Description]] "Futuristic assault rifle with an integrated dual combat sighting system. The 5.56 NATO cartridge combined with the short-stroke gas piston system make this a joy to shoot."),
	AdditionalHint = T(507516354956, --[[ModItemInventoryItemCompositeDef G36 AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Special 2-shot burst mode with improved critical chance and reduced recoil"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 17500,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 20,
	CategoryPair = "AssaultRifles",
	Caliber = "556",
	Damage = 23,
	AimAccuracy = 6,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 30,
	PointBlankBonus = 1,
	OverwatchAngle = 1023,
	Noise = 18,
	HandSlot = "TwoHanded",
	Entity = "Weapon_HKG36",
	fxClass = "G36",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"long_barrel_light",
				"BarrelLong",
				"BarrelHeavyLong",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"G36_SCOPE",
				"ThermalScope",
				"ReflexSightAdvanced",
				"SCOPE_G36_2",
				"PSG_DefaultScope",
				"_ReflexSIghtVigilance",
				"WideScope",
				"ScopeCOG",
				"ScopeCOGQuick",
				"LROptics",
				"ImprovedIronsight",
			},
			'DefaultComponent', "G36_SCOPE",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
				"ImprovisedSuppressor",
			},
			'DefaultComponent', "Compensator",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge_9",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"TacGrip",
				"VerticalGrip",
				"GrenadeLauncher",
				"Bipod_Under",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockLight",
				"foldable_StockNormal",
				"StockFolded",
			},
			'DefaultComponent', "foldable_StockNormal",
		}),
	},
	Color = "Khaki",
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 3000,
	ReloadAP = 3000,
	APStance = 4,
	PBbonus_base = 1,
	wep_base_recoil_mul = 98,
	burst_recoil_delta = 70,
	burst_selective = true,
	wep_base_hip_mul = 96,
	wep_base_snapshot_mul = 106,
	burst_shots = 2,
	weigth_held_mul = 128,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "Auto",
	recoil_mechanism = "Gas_Operated",
	rat_barrel_len = 480,
}

