UndefineClass('Gewehr98')
DefineClass.Gewehr98 = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 7.62 NATO ----- SNIPER",
	object_class = "SniperRifle",
	ScrapParts = 8,
	Reliability = 25,
	Icon = "UI/Icons/Weapons/Gewehr98",
	DisplayName = T(345864958607, --[[ModItemInventoryItemCompositeDef Gewehr98 DisplayName]] "Gewehr 98"),
	DisplayNamePlural = T(336053400117, --[[ModItemInventoryItemCompositeDef Gewehr98 DisplayNamePlural]] "Gewehr 98s"),
	Description = T(357007469557, --[[ModItemInventoryItemCompositeDef Gewehr98 Description]] "It is said that this Mauser design is the grandpa of all bolt action rifles. Even the modern hunting or military sniper rifles started here. "),
	AdditionalHint = T(973204362273, --[[ModItemInventoryItemCompositeDef Gewehr98 AdditionalHint]] "<description_hints>"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 2000,
	CanAppearInShop = true,
	CategoryPair = "Rifles",
	CanAppearStandard = false,
	Caliber = "792x57",
	Damage = 29,
	AimAccuracy = 6,
	CritChanceScaled = 20,
	MagazineSize = 5,
	WeaponRange = 30,
	PointBlankBonus = 1,
	OverwatchAngle = 651,
	Noise = 22,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Gewehr98",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ScopeCOG",
				"GewehrDefaultSight",
				"ImprovedIronsight",
				"ReflexSightAdvanced",
				"ScopeCOGQuick",
				"ThermalScope",
				"_ReflexSIghtVigilance",
				"WideScope",
				"LROpticsAdvanced",
				"PSG_DefaultScope",
			},
			'DefaultComponent', "GewehrDefaultSight",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "General",
			'AvailableComponents', {
				"Bolt_action",
			},
			'DefaultComponent', "Bolt_action",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	PreparedAttackType = "Both",
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	APStance = 5,
	default_long_barrel = true,
	PBbonus_base = -7,
	wep_base_recoil_mul = 88,
	wep_base_hip_mul = 82,
	wep_base_snapshot_mul = 126,
	weigth_held_mul = 132,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "BoltAction",
	recoil_mechanism = "Bolt_Action",
	rat_weigth = 4500,
	rat_barrel_len = 740,
}

