UndefineClass('Glock18')
DefineClass.Glock18 = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 9mm ----- PISTOL",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 70,
	Reliability = 80,
	Icon = "UI/Icons/Weapons/Glock18",
	DisplayName = T(353023377601, --[[ModItemInventoryItemCompositeDef Glock18 DisplayName]] "Glock 18"),
	DisplayNamePlural = T(170297988470, --[[ModItemInventoryItemCompositeDef Glock18 DisplayNamePlural]] "Glock 18s"),
	Description = T(510970424597, --[[ModItemInventoryItemCompositeDef Glock18 Description]] "Glock 17 with a fun switch and built in compensator. 9x19mm spray in the palm of your hand. "),
	AdditionalHint = T(850719596587, --[[ModItemInventoryItemCompositeDef Glock18 AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Swapping to this weapon is free, as long it is not dual-wielded\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Automatic firing modes"),
	UnitStat = "Marksmanship",
	Cost = 2800,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 30,
	CategoryPair = "Handguns",
	Caliber = "9mm",
	Damage = 16,
	MagazineSize = 15,
	WeaponRange = 16,
	PointBlankBonus = 1,
	OverwatchAngle = 2232,
	Noise = 18,
	Entity = "Weapon_Glock18",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ReflexSight",
				"ReflexSightAdvanced_Glock",
				"ImprovedIronsight",
				"_ReflexSIghtVigilance",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
				"Compensator_Glock",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'Modifiable', false,
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagLarge_3",
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
		"RunAndGun",
		"AutoFire",
	},
	ShootAP = 3000,
	ReloadAP = 3000,
	APStance = 1,
	PBbonus_base = 13,
	wep_base_recoil_mul = 116,
	burst_recoil_delta = 108,
	auto_recoil_delta = 108,
	long_recoil_delta = 108,
	wep_base_hip_mul = 116,
	wep_base_snapshot_mul = 70,
	burst_shots = 4,
	auto_shots = 12,
	weigth_held_mul = 106,
	Rat_swap_ap = 1,
	is_vanilla_firearm = true,
	Rat_cycling = "Auto",
	recoil_mechanism = "Striker_Fired",
	rat_weigth = 880,
	rat_barrel_len = 110,
}

