UndefineClass('HE_Grenade_RAT_1')
DefineClass.HE_Grenade_RAT_1 = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/HEGrenade",
	SubIcon = "Mod/TU6SADg/Images/bleed3.png",
	ItemType = "Grenade",
	DisplayName = T(414250153118, --[[ModItemInventoryItemCompositeDef HE_Grenade_RAT_1 DisplayName]] "Fragmentation Grenade"),
	DisplayNamePlural = T(185658627526, --[[ModItemInventoryItemCompositeDef HE_Grenade_RAT_1 DisplayNamePlural]] "Fragmentation Grenade"),
	Description = T(799012420616, --[[ModItemInventoryItemCompositeDef HE_Grenade_RAT_1 Description]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120>Inflicts <color EmStyle>Bleeding</color>"),
	AdditionalHint = "",
	UnitStat = "Explosives",
	Cost = 600,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "Grenade",
	MinMishapChance = 35,
	MaxMishapChance = 90,
	MinMishapRange = 0,
	CenterUnitDamageMod = 130,
	CenterObjDamageMod = 200,
	CenterAppliedEffects = {
		"Bleeding",
	},
	AreaObjDamageMod = 250,
	AreaAppliedEffects = {
		"Bleeding",
	},
	PenetrationClass = 4,
	DeathType = "BlowUp",
	BaseDamage = 35,
	Scatter = 4,
	BaseRange = 7,
	ThrowMaxRange = 17,
	CanBounce = false,
	InaccurateMaxOffset = 3000,
	Entity = "MilitaryCamp_Grenade_02",
	ActionIcon = "UI/Icons/Hud/throw_grenade",
}

