UndefineClass('HiPower')
DefineClass.HiPower = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 9mm ----- PISTOL",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 70,
	Reliability = 50,
	Icon = "UI/Icons/Weapons/Browning HiPower",
	DisplayName = T(757359398430, --[[ModItemInventoryItemCompositeDef HiPower DisplayName]] "Hi-Power"),
	DisplayNamePlural = T(702257960711, --[[ModItemInventoryItemCompositeDef HiPower DisplayNamePlural]] "Hi-Powers"),
	Description = T(328560663847, --[[ModItemInventoryItemCompositeDef HiPower Description]] "Used by both the Nazis and Allies during WWII. The hammer has a tendency to bite. "),
	AdditionalHint = T(345858616651, --[[ModItemInventoryItemCompositeDef HiPower AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Swapping to this weapon is free, as long it is not dual-wielded"),
	UnitStat = "Marksmanship",
	Cost = 750,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "9mm",
	Damage = 17,
	AimAccuracy = 4,
	MagazineSize = 13,
	WeaponRange = 16,
	PointBlankBonus = 1,
	OverwatchAngle = 2216,
	Noise = 18,
	Entity = "Weapon_Browning_HP",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
				"Compensator",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"ReflexSight",
				"_ReflexSIghtVigilance",
				"ReflexSightAdvanced_Glock",
				"ImprovedIronsight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagLarge_1",
				"MagNormal",
				"MagLargeFine_1",
				"MagNormalFine",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelShort_handgun",
				"BarrelShortImproved_handgun",
				"BarrelLong_handgun",
				"BarrelLongImproved_handgun",
				"BarrelLight",
				"long_barrel_light_handgun",
				"BarrelShort_Light_handgun",
			},
			'DefaultComponent', "BarrelNormal",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	APStance = 1,
	PBbonus_base = 12,
	wep_base_recoil_mul = 115,
	wep_base_hip_mul = 116,
	wep_base_snapshot_mul = 71,
	weigth_held_mul = 107,
	Rat_swap_ap = 1,
	is_vanilla_firearm = true,
	Rat_cycling = "SemiAuto",
	recoil_mechanism = "Short_Recoil",
	rat_weigth = 1050,
	rat_barrel_len = 110,
}

