UndefineClass('HK21')
DefineClass.HK21 = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 7.62 NATO ----- MG",
	object_class = "MachineGun",
	ScrapParts = 16,
	Reliability = 90,
	Icon = "UI/Icons/Weapons/HK21",
	DisplayName = T(897343205524, --[[ModItemInventoryItemCompositeDef HK21 DisplayName]] "HK21"),
	DisplayNamePlural = T(247511890606, --[[ModItemInventoryItemCompositeDef HK21 DisplayNamePlural]] "HK21s"),
	Description = T(527453635644, --[[ModItemInventoryItemCompositeDef HK21 Description]] "Combine an assault rifle with a machine gun and you get HK21. Unlike most hybrid guns, it performs each role extremely well."),
	AdditionalHint = T(671286970025, --[[ModItemInventoryItemCompositeDef HK21 AdditionalHint]] "<description_hints>"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 19025,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "MachineGuns",
	Caliber = "762NATO",
	Damage = 30,
	AimAccuracy = 4,
	MagazineSize = 20,
	WeaponRange = 34,
	PointBlankBonus = 1,
	OverwatchAngle = 695,
	Noise = 22,
	HandSlot = "TwoHanded",
	Entity = "Weapon_HK21",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong",
				"BarrelLongImproved",
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelShort",
				"BarrelShortImproved",
				"long_barrel_light",
				"BarrelShort_Light",
				"BarrelLight",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"DefaultMuzzle_HK21",
				"MuzzleBooster",
				"Compensator",
			},
			'DefaultComponent', "DefaultMuzzle_HK21",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovedIronsight",
				"LROptics",
				"LROpticsAdvanced",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
				"WideScope",
				"_ReflexSIghtVigilance",
				"PSG_DefaultScope",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockNormal",
				"StockLight",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"TacGrip",
				"VerticalGrip",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge_8",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	APStance = 5,
	PBbonus_base = -2,
	wep_base_recoil_mul = 89,
	wep_base_hip_mul = 93,
	wep_base_snapshot_mul = 124,
	weigth_held_mul = 157,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "Auto",
	recoil_mechanism = "Roller_Delayed",
	rat_weigth = 8000,
	rat_barrel_len = 530,
}

