UndefineClass('M14SAW_AUTO')
DefineClass.M14SAW_AUTO = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 7.62 NATO ----- ASSAULT",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	Reliability = 80,
	Icon = "UI/Icons/Weapons/M14",
	SubIcon = "Mod/cfahRED/Images/m143.png",
	DisplayName = T(664499471719, --[[ModItemInventoryItemCompositeDef M14SAW_AUTO DisplayName]] "M-14"),
	DisplayNamePlural = T(300513013967, --[[ModItemInventoryItemCompositeDef M14SAW_AUTO DisplayNamePlural]] "M-14s"),
	colorStyle = "",
	Description = T(251899153523, --[[ModItemInventoryItemCompositeDef M14SAW_AUTO Description]] "Take a Garand rifle, then make it heavier and capable of firing full auto. Simply put, it's a Frankenstein monster."),
	AdditionalHint = T(419078734073, --[[ModItemInventoryItemCompositeDef M14SAW_AUTO AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Military variant with burst fire and auto fire modes\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Has a big recoil penalty"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 7200,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "762NATO",
	Damage = 29,
	AimAccuracy = 4,
	MagazineSize = 10,
	WeaponRange = 28,
	PointBlankBonus = 1,
	OverwatchAngle = 870,
	HandSlot = "TwoHanded",
	Entity = "Weapon_M14",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong",
				"BarrelLongImproved",
				"BarrelNormal",
				"BarrelShort",
				"BarrelShortImproved",
				"BarrelHeavyLong",
				"BarrelLight",
				"long_barrel_light",
				"BarrelShort_Light",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockNormal",
				"StockLight",
			},
			'DefaultComponent', "StockHeavy",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagLarge_5",
				"MagLargeFine_5",
				"MagNormal",
				"MagNormalFine",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"GrenadeLauncher_M14",
				"TacGrip_M14",
				"VerticalGrip_M14",
				"Bipod_Under",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"M14_Default_Muzzle",
				"Compensator",
				"Suppressor",
				"ImprovisedSuppressor",
				"MuzzleBooster",
			},
			'DefaultComponent', "M14_Default_Muzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LaserDot",
				"FlashlightDot",
				"UVDot",
				"Flashlight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovedIronsight",
				"LROptics",
				"LROpticsAdvanced",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
				"WideScope",
				"_ReflexSIghtVigilance",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "General",
			'Modifiable', false,
			'AvailableComponents', {
				"m14_component_recoil",
			},
			'DefaultComponent', "m14_component_recoil",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	APStance = 4,
	wep_base_recoil_mul = 89,
	auto_recoil_delta = 125,
	long_recoil_delta = 125,
	wep_base_hip_mul = 97,
	wep_base_snapshot_mul = 109,
	weigth_held_mul = 137,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "Auto",
	recoil_mechanism = "Gas_Operated",
	rat_weigth = 5220,
	rat_barrel_len = 457,
	PBbonus_base = -1,
}

