UndefineClass('M24Sniper')
DefineClass.M24Sniper = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 7.62 NATO ----- SNIPER",
	object_class = "SniperRifle",
	ScrapParts = 14,
	Reliability = 44,
	Icon = "UI/Icons/Weapons/M24",
	DisplayName = T(756458402136, --[[ModItemInventoryItemCompositeDef M24Sniper DisplayName]] "M24"),
	DisplayNamePlural = T(303379849627, --[[ModItemInventoryItemCompositeDef M24Sniper DisplayNamePlural]] "M24s"),
	Description = T(511660833322, --[[ModItemInventoryItemCompositeDef M24Sniper Description]] "US Army sniper weapon system that replaced the M21 (based on the M14). Apparently semi-auto was still not up to par with what snipers needed in terms of reliability and accuracy that bolt action can provide. "),
	AdditionalHint = T(713886804400, --[[ModItemInventoryItemCompositeDef M24Sniper AdditionalHint]] "<description_hints>"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 8100,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 2,
	RestockWeight = 50,
	CategoryPair = "Rifles",
	Caliber = "762NATO",
	Damage = 33,
	AimAccuracy = 8,
	CritChanceScaled = 30,
	MagazineSize = 5,
	IgnoreCoverReduction = 1,
	WeaponRange = 32,
	PointBlankBonus = 1,
	OverwatchAngle = 772,
	Noise = 22,
	HandSlot = "TwoHanded",
	Entity = "Weapon_M24",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockLight",
				"StockNormal",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"LROptics",
				"LROpticsAdvanced",
				"ReflexSight",
				"ScopeCOG",
				"ThermalScope",
				"PSG_DefaultScope",
				"WideScope",
				"_ReflexSIghtVigilance",
			},
			'DefaultComponent', "LROptics",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Suppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "General",
			'AvailableComponents', {
				"Bolt_action",
			},
			'DefaultComponent', "Bolt_action",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	PreparedAttackType = "Both",
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	APStance = 5,
	default_long_barrel = true,
	PBbonus_base = -3,
	wep_base_recoil_mul = 91,
	wep_base_hip_mul = 89,
	wep_base_snapshot_mul = 119,
	weigth_held_mul = 137,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "BoltAction",
	recoil_mechanism = "Bolt_Action",
	rat_weigth = 5200,
	rat_barrel_len = 610,
}

