UndefineClass('M4Commando')
DefineClass.M4Commando = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 5.56  ----- SMG",
	object_class = "SubmachineGun",
	ScrapParts = 10,
	Reliability = 80,
	Icon = "UI/Icons/Weapons/Commando",
	DisplayName = T(314782459071, --[[ModItemInventoryItemCompositeDef M4Commando DisplayName]] "Commando"),
	DisplayNamePlural = T(839790871682, --[[ModItemInventoryItemCompositeDef M4Commando DisplayNamePlural]] "Commandos"),
	Description = T(967536201582, --[[ModItemInventoryItemCompositeDef M4Commando Description]] "How would you make a short barrel M16 work? Answer - lower muzzle velocity and huge muzzle flash."),
	AdditionalHint = T(502423132983, --[[ModItemInventoryItemCompositeDef M4Commando AdditionalHint]] "<description_hints>"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 16750,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 30,
	CategoryPair = "SubmachineGuns",
	Caliber = "556",
	Damage = 22,
	AimAccuracy = 4,
	CritChanceScaled = 30,
	MagazineSize = 20,
	WeaponRange = 24,
	PointBlankBonus = 1,
	OverwatchAngle = 1429,
	HandSlot = "TwoHanded",
	Entity = "Weapon_CAR15",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'AvailableComponents', {
				"Handguard_Commando",
				"VerticalGrip_Commando",
				"GrenadeLauncher_Commando",
			},
			'DefaultComponent', "Handguard_Commando",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
				"MagLarge",
				"MagLargeFine",
				"R_MagQuickLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNormal",
				"StockLight",
				"StockNo",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ScopeCOG",
				"ThermalScope",
				"ReflexSightAdvanced",
				"ScopeCOGQuick",
				"_ReflexSIghtVigilance",
				"WideScope",
				"ImprovedIronsight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"MuzzleBooster",
				"Suppressor",
				"ImprovisedSuppressor",
			},
			'DefaultComponent', "Compensator",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	ShootAP = 3000,
	ReloadAP = 3000,
	PBbonus_base = 7,
	wep_base_recoil_mul = 116,
	placeholder_recoil = 108,
	wep_base_hip_mul = 108,
	wep_base_snapshot_mul = 86,
	weigth_held_mul = 117,
	is_vanilla_firearm = true,
	Rat_cycling = "Auto",
	recoil_mechanism = "Gas_Operated",
	rat_weigth = 2430,
	rat_barrel_len = 250,
}

