UndefineClass('MG42')
DefineClass.MG42 = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 7.62 NATO ----- MG",
	object_class = "MachineGun",
	ScrapParts = 12,
	Reliability = 90,
	Icon = "UI/Icons/Weapons/MG42",
	DisplayName = T(675844784736, --[[ModItemInventoryItemCompositeDef MG42 DisplayName]] "MG42"),
	DisplayNamePlural = T(769933732561, --[[ModItemInventoryItemCompositeDef MG42 DisplayNamePlural]] "MG42s"),
	Description = T(587184991673, --[[ModItemInventoryItemCompositeDef MG42 Description]] "With its incredible rate of fire, the MG42 provides amazing suppression capacity. She might be old but she's German."),
	AdditionalHint = T(386845693893, --[[ModItemInventoryItemCompositeDef MG42 AdditionalHint]] "<description_hints>"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Marksmanship",
	Cost = 4200,
	CanAppearInShop = true,
	MaxStock = 1,
	RestockWeight = 80,
	CategoryPair = "MachineGuns",
	CanAppearStandard = false,
	Caliber = "792x57",
	Damage = 28,
	MagazineSize = 50,
	WeaponRange = 38,
	PointBlankBonus = 1,
	OverwatchAngle = 571,
	Noise = 22,
	HandSlot = "TwoHanded",
	Entity = "Weapon_MG42",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'Modifiable', false,
			'AvailableComponents', {
				"Bipod_MG42",
			},
			'DefaultComponent', "Bipod_MG42",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	APStance = 5,
	PBbonus_base = -4,
	wep_base_recoil_mul = 82,
	wep_base_hip_mul = 92,
	wep_base_snapshot_mul = 138,
	weigth_held_mul = 182,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "Auto",
	recoil_mechanism = "Short_Recoil",
	rat_weigth = 11600,
	rat_barrel_len = 550,
}

