UndefineClass('MG58')
DefineClass.MG58 = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "MachineGun",
	ScrapParts = 12,
	Reliability = 95,
	Icon = "UI/Icons/Weapons/MG58.png",
	DisplayName = T(104887107175, --[[ModItemInventoryItemCompositeDef MG58 DisplayName]] "MG58"),
	DisplayNamePlural = T(219033710999, --[[ModItemInventoryItemCompositeDef MG58 DisplayNamePlural]] "MG58s"),
	Description = T(876768282697, --[[ModItemInventoryItemCompositeDef MG58 Description]] "Modified MG42, fitted with a Kompositum 58 barrel, 7.62x51mm caliber receiver, improved ironsights and some internal improvements. The MG58 is born. "),
	AdditionalHint = T(240845249658, --[[ModItemInventoryItemCompositeDef MG58 AdditionalHint]] "<description_hints>"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 1200,
	Caliber = "762NATO",
	Damage = 30,
	MagazineSize = 50,
	WeaponRange = 40,
	PointBlankBonus = 1,
	OverwatchAngle = 571,
	Noise = 22,
	HandSlot = "TwoHanded",
	Entity = "Weapon_MG42",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'Modifiable', false,
			'AvailableComponents', {
				"Bipod_MG42",
			},
			'DefaultComponent', "Bipod_MG42",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'Modifiable', false,
			'AvailableComponents', {
				"ImprovedIronsight",
			},
			'DefaultComponent', "ImprovedIronsight",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	APStance = 5,
	PBbonus_base = -3,
	wep_base_recoil_mul = 82,
	placeholder_recoil = 90,
	wep_base_hip_mul = 92,
	wep_base_snapshot_mul = 138,
	long_shots = 7,
	weigth_held_mul = 182,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "Auto",
	recoil_mechanism = "Gas_Operated",
}

