UndefineClass('RPK74')
DefineClass.RPK74 = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 5.45 -----MG",
	object_class = "MachineGun",
	ScrapParts = 16,
	Reliability = 95,
	Icon = "UI/Icons/Weapons/RPK74",
	DisplayName = T(389543404174, --[[ModItemInventoryItemCompositeDef RPK74 DisplayName]] "RPK-74"),
	DisplayNamePlural = T(231030056246, --[[ModItemInventoryItemCompositeDef RPK74 DisplayNamePlural]] "RPK-74s"),
	Description = T(358707545013, --[[ModItemInventoryItemCompositeDef RPK74 Description]] "Built upon the AK platform with a thicker barrel and other small changes to allow for better sustained fire capability. This general purpose machine gun is meant to be a squad force multiplier with easy operation, integration, and ammo compatibility with other AK weapons."),
	AdditionalHint = T(553717282985, --[[ModItemInventoryItemCompositeDef RPK74 AdditionalHint]] "<description_hints>"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 8800,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 2,
	RestockWeight = 30,
	CategoryPair = "MachineGuns",
	Caliber = "545x39",
	Damage = 22,
	MagazineSize = 45,
	WeaponRange = 32,
	PointBlankBonus = 1,
	OverwatchAngle = 815,
	Noise = 22,
	HandSlot = "TwoHanded",
	Entity = "Weapon_RPK74",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelLight",
				"rpk_to762wp",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
				"MagQuick",
				"MagLarge_2",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"RPK74_Hanguard_Basic",
				"RPK74_VerticalGrip",
			},
			'DefaultComponent', "RPK74_Hanguard_Basic",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ScopeCOG",
				"ThermalScope",
				"LROpticsAdvanced",
				"ScopeCOGQuick",
				"ReflexSightAdvanced",
				"_ReflexSIghtVigilance",
				"WideScope",
				"LROptics_DragunovDefault",
				"UVDot_Anaconda",
				"LaserDot_Anaconda",
				"ImprovedIronsight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"MuzzleBooster",
				"Suppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNormal",
				"StockLight",
			},
			'DefaultComponent', "StockNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	APStance = 4,
	PBbonus_base = -3,
	wep_base_recoil_mul = 91,
	placeholder_recoil = 98,
	wep_base_hip_mul = 91,
	wep_base_snapshot_mul = 119,
	weigth_held_mul = 140,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "Auto",
	recoil_mechanism = "Gas_Operated",
	rat_weigth = 5600,
	rat_barrel_len = 580,
}

