UndefineClass('TearGasGrenade_RAT_1')
DefineClass.TearGasGrenade_RAT_1 = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/TearGasGrenade",
	ItemType = "GrenadeGas",
	DisplayName = T(623032870138, --[[ModItemInventoryItemCompositeDef TearGasGrenade_RAT_1 DisplayName]] "Tear Gas Grenade"),
	DisplayNamePlural = T(878963072084, --[[ModItemInventoryItemCompositeDef TearGasGrenade_RAT_1 DisplayNamePlural]] "Tear Gas Grenades"),
	AdditionalHint = T(472147717368, --[[ModItemInventoryItemCompositeDef TearGasGrenade_RAT_1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Blinded</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become <color EmStyle>grazing</color> hits\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent"),
	UnitStat = "Explosives",
	Cost = 800,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 25,
	CategoryPair = "Grenade",
	MinMishapChance = 35,
	MaxMishapChance = 90,
	MinMishapRange = 0,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 0,
	Scatter = 4,
	AttackAP = 4000,
	InaccurateMaxOffset = 4000,
	Noise = 0,
	aoeType = "teargas",
	Entity = "Weapon_MolotovCocktail",
	ActionIcon = "UI/Icons/Hud/tear_gas_grenade",
}

