UndefineClass('TexRevolver')
DefineClass.TexRevolver = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ .44 cal ----- REVOLVER",
	object_class = "Revolver",
	ScrapParts = 8,
	RepairCost = 50,
	Reliability = 85,
	Icon = "UI/Icons/Weapons/TexRevolver",
	DisplayName = T(367644255554, --[[ModItemInventoryItemCompositeDef TexRevolver DisplayName]] "Custom Six-Shooter"),
	DisplayNamePlural = T(702389656420, --[[ModItemInventoryItemCompositeDef TexRevolver DisplayNamePlural]] "Custom Six-Shooters"),
	Description = T(372618644216, --[[ModItemInventoryItemCompositeDef TexRevolver Description]] "A custom-built revolver with a 10-inch barrel and ivory handle featuring TEX engraved in a 14K gold."),
	AdditionalHint = T(596143246468, --[[ModItemInventoryItemCompositeDef TexRevolver AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Tex has reduced penalty when using Dual Shot with his revolvers\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Single action"),
	UnitStat = "Marksmanship",
	Cost = 2000,
	locked = true,
	Caliber = "44CAL",
	Damage = 21,
	AimAccuracy = 6,
	CritChanceScaled = 50,
	MagazineSize = 6,
	WeaponRange = 18,
	PointBlankBonus = 1,
	OverwatchAngle = 2162,
	Noise = 18,
	Entity = "Weapon_Colt",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Trigger",
			'Modifiable', false,
			'AvailableComponents', {
				"single_action_tex",
			},
			'DefaultComponent', "single_action_tex",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong_handgun",
				"BarrelNormal",
				"BarrelShort_handgun",
				"BarrelLight",
				"long_barrel_light_handgun",
				"BarrelShort_Light_handgun",
			},
			'DefaultComponent', "BarrelNormal",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	APStance = 1,
	PBbonus_base = 11,
	wep_base_recoil_mul = 114,
	wep_base_hip_mul = 110,
	wep_base_snapshot_mul = 70,
	Rat_swap_ap = 1,
	is_vanilla_firearm = true,
	Rat_cycling = "SingleAction",
	recoil_mechanism = "Revolver",
}

