UndefineClass('UZI')
DefineClass.UZI = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ 9mm ----- SMG",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	Reliability = 75,
	Icon = "UI/Icons/Weapons/UZI",
	DisplayName = T(675261533661, --[[ModItemInventoryItemCompositeDef UZI DisplayName]] "UZI"),
	DisplayNamePlural = T(656069887722, --[[ModItemInventoryItemCompositeDef UZI DisplayNamePlural]] "UZIs"),
	Description = T(292309700158, --[[ModItemInventoryItemCompositeDef UZI Description]] "Designed as a personal defense weapon for rear echelon troops in the Israel Defense Forces. Intended to be used with a buttstock, but regularly wielded one-handed. Can deliver a lot of lead though accuracy may vary. "),
	AdditionalHint = T(862681616280, --[[ModItemInventoryItemCompositeDef UZI AdditionalHint]] "<description_hints>"),
	UnitStat = "Marksmanship",
	Cost = 1600,
	CanAppearInShop = true,
	MaxStock = 4,
	CategoryPair = "SubmachineGuns",
	Caliber = "9mm",
	Damage = 18,
	MagazineSize = 25,
	WeaponRange = 18,
	PointBlankBonus = 1,
	OverwatchAngle = 1410,
	Entity = "Weapon_Uzi",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelLong_handgun",
				"BarrelLongImproved_handgun",
				"long_barrel_light_handgun",
				"BarrelLight_handgun",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge_4",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
				"MagLargeFine",
				"MagNormalFine",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"ReflexSight",
				"ReflexSightAdvanced",
				"_ReflexSIghtVigilance",
				"ImprovedIronsight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNo",
				"StockHeavy",
				"StockLight",
			},
			'DefaultComponent', "StockNo",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"DualShot",
		"RunAndGun",
		"CancelShot",
	},
	ShootAP = 3000,
	ReloadAP = 3000,
	PBbonus_base = 8,
	wep_base_recoil_mul = 108,
	wep_base_hip_mul = 108,
	wep_base_snapshot_mul = 86,
	weigth_held_mul = 119,
	Rat_swap_ap = 1,
	is_vanilla_firearm = true,
	Rat_cycling = "Auto",
	recoil_mechanism = "Blowback",
	rat_weigth = 2700,
	rat_barrel_len = 250,
}

