UndefineClass('Winchester1894')
DefineClass.Winchester1894 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "------------ .44 cal ----- SNIPER",
	object_class = "AssaultRifle",
	ScrapParts = 8,
	Reliability = 95,
	Icon = "UI/Icons/Weapons/Winchester",
	DisplayName = T(256059833693, --[[ModItemInventoryItemCompositeDef Winchester1894 DisplayName]] "Winchester 1894"),
	DisplayNamePlural = T(343389302702, --[[ModItemInventoryItemCompositeDef Winchester1894 DisplayNamePlural]] "Winchester 1894s"),
	Description = T(462262512623, --[[ModItemInventoryItemCompositeDef Winchester1894 Description]] 'One of the guns that "won the West". The magazine tube holds more ammo than your standard bolt action rifle. How this one got in this part of the world is anyone\'s guess.'),
	AdditionalHint = T(709693708737, --[[ModItemInventoryItemCompositeDef Winchester1894 AdditionalHint]] "<description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Lever action\n"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 3000,
	CanAppearInShop = true,
	CategoryPair = "Rifles",
	CanAppearStandard = false,
	Caliber = "44CAL",
	Damage = 23,
	AimAccuracy = 3,
	CritChanceScaled = 30,
	MagazineSize = 9,
	WeaponRange = 28,
	PointBlankBonus = 1,
	OverwatchAngle = 1053,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Winchester",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong",
				"BarrelNormal",
				"BarrelShort_Winchester",
				"BarrelLight",
				"long_barrel_light",
				"winni_to54r",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Suppressor",
				"ImprovisedSuppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovedIronsight",
				"LROptics",
				"LROpticsAdvanced",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
				"_ReflexSIghtVigilance",
				"WideScope",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "General",
			'Modifiable', false,
			'AvailableComponents', {
				"lever_action",
			},
			'DefaultComponent', "lever_action",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	PreparedAttackType = "Both",
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	APStance = 4,
	PBbonus_base = 0,
	wep_base_recoil_mul = 97,
	wep_base_hip_mul = 93,
	wep_base_snapshot_mul = 107,
	weigth_held_mul = 121,
	Rat_swap_ap = 3,
	is_vanilla_firearm = true,
	Rat_cycling = "LeverAction",
	recoil_mechanism = "Lever_Action",
	rat_weigth = 3000,
	rat_barrel_len = 540,
}

